-- ============================================================
-- FAZZXXY WALLET DEMO - SUPABASE SETUP
-- Jalankan SEMUA SQL ini di Supabase > SQL Editor.
-- Ini hanya untuk saldo DEMO, bukan sistem uang sungguhan.
-- ============================================================

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  phone text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.wallets (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance numeric(14,2) not null default 100000,
  created_at timestamptz not null default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null check (type in ('in','out')),
  amount numeric(14,2) not null check (amount > 0),
  counterparty_phone text not null,
  created_at timestamptz not null default now()
);

create index if not exists profiles_phone_idx on public.profiles(phone);
create index if not exists transactions_user_idx on public.transactions(user_id, created_at desc);

alter table public.profiles enable row level security;
alter table public.wallets enable row level security;
alter table public.transactions enable row level security;

drop policy if exists "profiles read authenticated" on public.profiles;
create policy "profiles read authenticated"
on public.profiles for select
to authenticated
using (true);

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own"
on public.profiles for insert
to authenticated
with check ((select auth.uid()) = id);

drop policy if exists "profiles update own" on public.profiles;
create policy "profiles update own"
on public.profiles for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);

drop policy if exists "wallet own read" on public.wallets;
create policy "wallet own read"
on public.wallets for select
to authenticated
using ((select auth.uid()) = user_id);

drop policy if exists "wallet own insert" on public.wallets;
create policy "wallet own insert"
on public.wallets for insert
to authenticated
with check ((select auth.uid()) = user_id);

drop policy if exists "tx own read" on public.transactions;
create policy "tx own read"
on public.transactions for select
to authenticated
using ((select auth.uid()) = user_id);

-- Jangan beri client izin UPDATE saldo.
-- Saldo hanya berubah lewat fungsi transfer di bawah.

create or replace function public.transfer_demo_balance(
  p_receiver_phone text,
  p_amount numeric
)
returns json
language plpgsql
security definer
set search_path = ''
as $$
declare
  sender_id uuid := (select auth.uid());
  receiver_id uuid;
  sender_phone text;
  sender_balance numeric;
begin
  if sender_id is null then
    raise exception 'Belum login';
  end if;

  if p_amount is null or p_amount <= 0 then
    raise exception 'Nominal tidak valid';
  end if;

  select id, phone
    into receiver_id, sender_phone
    from public.profiles
   where id = sender_id;

  if receiver_id is null then
    raise exception 'Profil pengirim tidak ditemukan';
  end if;

  select id into receiver_id
    from public.profiles
   where phone = p_receiver_phone;

  if receiver_id is null then
    raise exception 'Nomor penerima belum terdaftar';
  end if;

  if receiver_id = sender_id then
    raise exception 'Tidak bisa kirim ke akun sendiri';
  end if;

  -- Lock both wallet rows so two simultaneous transfers cannot
  -- spend the same balance.
  select balance into sender_balance
    from public.wallets
   where user_id = sender_id
   for update;

  if sender_balance is null then
    raise exception 'Wallet pengirim tidak ditemukan';
  end if;

  if sender_balance < p_amount then
    raise exception 'Saldo tidak cukup';
  end if;

  update public.wallets
     set balance = balance - p_amount
   where user_id = sender_id;

  update public.wallets
     set balance = balance + p_amount
   where user_id = receiver_id;

  insert into public.transactions(user_id,type,amount,counterparty_phone)
  values
    (sender_id,'out',p_amount,p_receiver_phone),
    (receiver_id,'in',p_amount,sender_phone);

  return json_build_object('ok', true, 'amount', p_amount);
end;
$$;

revoke execute on function public.transfer_demo_balance(text,numeric) from public;
revoke execute on function public.transfer_demo_balance(text,numeric) from anon;
grant execute on function public.transfer_demo_balance(text,numeric) to authenticated;

-- Setelah menjalankan SQL:
-- 1. Di Supabase Authentication, matikan "Confirm email" untuk demo ini,
--    karena aplikasi membuat alamat email internal dari nomor HP.
-- 2. Ambil Project URL dan Publishable key.
-- 3. Tempel keduanya ke index.html.
-- 4. JANGAN gunakan service_role/secret key di HTML.
